// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DeleteallproductsusingTIMESTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Dispose();
  }
  [Test]
  public void DeleteallproductsusingTIMES() {
    // Test name: 03.Delete all products using TIMES
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.saucedemo.com/");
    // 2 | setWindowSize | 1280x960 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 960);
    // 3 | type | xpath=//input[@id="user-name"] | standard_user
    driver.FindElement(By.XPath("//input[@id=\"user-name\"]")).SendKeys("standard_user");
    // 4 | type | xpath=//input[@id="password"] | secret_sauce
    driver.FindElement(By.XPath("//input[@id=\"password\"]")).SendKeys("secret_sauce");
    // 5 | click | xpath=//input[@id="login-button"] | 
    driver.FindElement(By.XPath("//input[@id=\"login-button\"]")).Click();
    // 6 | assertText | xpath=//span[@class="title"] | Products
    Assert.That(driver.FindElement(By.XPath("//span[@class=\"title\"]")).Text, Is.EqualTo("Products"));
    // 7 | click | xpath=//a[@class="shopping_cart_link"] | 
    driver.FindElement(By.XPath("//a[@class=\"shopping_cart_link\"]")).Click();
    // 8 | executeScript | return 6 | times
    vars["times"] = js.ExecuteScript("return 6");
    // 9 | times | 6 | 
    var times = 6;
    for(int i = 0; i < times; i++) {
      // 10 | click | //button[@class="btn btn_secondary btn_small cart_button"] | 
      driver.FindElement(By.XPath("//button[@class=\"btn btn_secondary btn_small cart_button\"]")).Click();
      // 11 | end |  | 
    }
    // 12 | assertElementNotPresent | xpath=//div[@class="inventory_item_name"] | 
    {
      var elements = driver.FindElements(By.XPath("//div[@class=\"inventory_item_name\"]"));
      Assert.True(elements.Count == 0);
    }
  }
}
