// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginwithInvalidUserandRetryTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Dispose();
    }
    [Test]
    public void LoginwithInvalidUserandRetry()
    {
        // Test name: 01.Login with Invalid User and Retry
        // Step # | name | target | value
        // 1 | open | / | 
        driver.Navigate().GoToUrl("https://www.saucedemo.com/");
        // 2 | setWindowSize | 1280x960 | 
        driver.Manage().Window.Size = new System.Drawing.Size(1280, 960);
        // 3 | type | xpath=//input[@id="user-name"] | user123
        driver.FindElement(By.XPath("//input[@id=\"user-name\"]")).SendKeys("user123");
        // 4 | type | xpath=//input[@id="password"] | secret_sauce
        driver.FindElement(By.XPath("//input[@id=\"password\"]")).SendKeys("secret_sauce");
        // 5 | click | xpath=//input[@id="login-button"] | 
        driver.FindElement(By.XPath("//input[@id=\"login-button\"]")).Click();
        // 6 | storeText | xpath=//h3[@data-test="error"] | errorMessage
        vars["errorMessage"] = driver.FindElement(By.XPath("//h3[@data-test=\"error\"]")).Text;
        // 7 | verifyText | xpath=//h3[@data-test="error"] | Epic sadface: Username and password do not match any user in this service
        Assert.That(driver.FindElement(By.XPath("//h3[@data-test=\"error\"]")).Text, Is.EqualTo("Epic sadface: Username and password do not match any user in this service"));
        // 8 | if | ${errorMessage} == "Epic sadface: Username and password do not match any user in this service" | 
        if ((Boolean)js.ExecuteScript("return (arguments[0] == \'Epic sadface: Username and password do not match any user in this service\')", vars["errorMessage"]))
        {
            // 9 | echo | Wrong username | 
            Console.WriteLine("Wrong username");
            // 10 | type | xpath=//input[@id="user-name"] | standard_user
            driver.FindElement(By.XPath("//input[@id=\"user-name\"]")).SendKeys("standard_user");
            // 11 | type | xpath=//input[@id="password"] | secret_sauce
            driver.FindElement(By.XPath("//input[@id=\"password\"]")).SendKeys("secret_sauce");
            // 12 | click | xpath=//input[@id="login-button"] | 
            driver.FindElement(By.XPath("//input[@id=\"login-button\"]")).Click();
            // 13 | assertText | xpath=//span[@class="title"] | Products
            Assert.That(driver.FindElement(By.CssSelector("span.title")).Text, Is.EqualTo("Products"));

            // 14 | echo | Successful login | 
            Console.WriteLine("Successful login");
            // 15 | end |  | 
        }
        // 16 | close |  | 
        driver.Close();
    }
}
