// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginandLogoutTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Dispose();
    }
    [Test]
    public void LoginandLogout()
    {
        // Test name: 02.Login and Logout
        // Step # | name | target | value
        // 1 | open | / | 
        driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
        // 2 | setWindowSize | 1280x960 | 
        driver.Manage().Window.Size = new System.Drawing.Size(1280, 960);
        // 3 | assertText | xpath=//a[@id="btn-make-appointment"] | Make Appointment
        Assert.That(driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Text, Is.EqualTo("Make Appointment"));
        // 4 | click | xpath=//a[@id="btn-make-appointment"] | 
        driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Click();
        // 5 | assertText | xpath=//div[@class ="col-sm-12 text-center"]/h2 | Login
        Assert.That(driver.FindElement(By.XPath("//div[@class =\"col-sm-12 text-center\"]/h2")).Text, Is.EqualTo("Login"));
        // 6 | assertText | xpath=//div[@class ="col-sm-12 text-center"]/p[@class="lead"] | Please login to make appointment.
        Assert.That(driver.FindElement(By.XPath("//div[@class =\"col-sm-12 text-center\"]/p[@class=\"lead\"]")).Text, Is.EqualTo("Please login to make appointment."));
        // 7 | assertText | xpath=//label[@for="txt-username"] | Username
        Assert.That(driver.FindElement(By.XPath("//label[@for=\"txt-username\"]")).Text, Is.EqualTo("Username"));
        // 8 | assertText | xpath=//label[@for="txt-password"] | Password
        Assert.That(driver.FindElement(By.XPath("//label[@for=\"txt-password\"]")).Text, Is.EqualTo("Password"));
        // 9 | type | xpath=//input[@id="txt-username"] | John Doe
        driver.FindElement(By.XPath("//input[@id=\"txt-username\"]")).SendKeys("John Doe");
        // 10 | type | xpath=//input[@id="txt-password"] | ThisIsNotAPassword
        driver.FindElement(By.XPath("//input[@id=\"txt-password\"]")).SendKeys("ThisIsNotAPassword");
        // 11 | click | xpath=//button[@id="btn-login"] | 
        driver.FindElement(By.XPath("//button[@id=\"btn-login\"]")).Click();
        // 12 | assertText | xpath=//div[@class="col-sm-12 text-center"]/h2 | Make Appointment
        Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-sm-12 text-center\"]/h2")).Text, Is.EqualTo("Make Appointment"));
        // 13 | click | xpath=//a[@id="menu-toggle"] | 
        driver.FindElement(By.XPath("//a[@id=\"menu-toggle\"]")).Click();
        // 14 | click | xpath=//a[@href="authenticate.php?logout"] | 
        driver.FindElement(By.XPath("//a[@href=\"authenticate.php?logout\"]")).Click();
        // 15 | click | xpath=//a[@id="menu-toggle"] | 
        driver.FindElement(By.XPath("//a[@id=\"menu-toggle\"]")).Click();
        // 16 | verifyElementPresent | xpath=//a[@href="profile.php#login"] | 
        var elements = driver.FindElements(By.XPath("//a[@href=\"profile.php#login\"]"));
        object value = Assert.True(elements.Count > 0);
        // 17 | close |  | 
        driver.Close();
    }
}